### ISSUE TITLE
1.19.0 fails to initialize

### ISSUE THREAD

**Issue by dtmichel** [skodaconnect/homeassistant-myskoda#570]
**Describe the bug**
The integration fails to initialize.

**Is this working in MySkoda app?***
Yes

**Latest working release**
1.18.0

**Debug logs**

> Error setting up entry xyz@abc.example for myskoda
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myskoda/__init__.py", line 95, in async_setup_entry
    cached_vins: list = entry.data[VINLIST]
                        ~~~~~~~~~~^^^^^^^^^
KeyError: 'vins'

**Comment by WebSpider** [comment]
This is related to #502

**Comment by WebSpider** [comment]
I am unable to reproduce this here. Can you see if you can set your logging to debug and restart the integration?

**Comment by prvakt** [comment]
same here

Fist I have just updated and got migration error message but there was no error in the log
Afterwards deleted my hub and created again with very same error as above

**Comment by dtmichel** [comment]
I enabled the debug mode for the integration and restarted Home Assistant, as I was not able to restart only the integration. The option to do so was not available. The additional restart of HA seems to have fixed the migration error for the MySkoda integration. Now it appears that the Skoda API is down, as all sensors are unavailable and the API returns errors:

> Logger: myskoda.rest_api
Source: /usr/local/lib/python3.13/site-packages/myskoda/rest_api.py:105
First occurred: 11:08:42 (3 occurrences)
Last logged: 11:08:57
Invalid status for GET request to /v1/charging/my-vin: 500
Invalid status for GET request to /v2/vehicle-status/my-vin: 500
Invalid status for GET request to /v1/vehicle-health-report/warning-lights/my-vin: 500
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myskoda/rest_api.py", line 99, in _make_request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1161, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/charging/my-vin'

> Logger: myskoda.myskoda
Source: custom_components/myskoda/coordinator.py:468
integration: MySkoda (documentation, issues)
First occurred: 11:11:23 (2 occurrences)
Last logged: 11:12:05
Requesting CHARGING failed: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/charging/my-vin', continue
Requesting VEHICLE_HEALTH_INSPECTION failed: 500, message='Internal Server Error', url='https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-health-report/warning-lights/my-vin', continue

So, it appears the restart fixed the issue but Skoda API is down. The App is not working either.

**Comment by prvakt** [comment]
@WebSpider found the problem - VINLIST is not initialized, line 95 in `__init__.py` must be changed to `cached_vins: list = entry.data.get(VINLIST, [])`

**Comment by prvakt** [comment]
or I was just lucky and problem was fixed independetly from my code change?

**Comment by WebSpider** [comment]
Ah, found the issue. The migration of the config schema was incomplete. I will fix this, and apply the suggestion from @prvakt just to be sure.

**Comment by WebSpider** [comment]
This should be fixed with v1.19.1

**Comment by une18** [comment]
This error originated from a custom integration.

Logger: custom_components.myskoda
Source: custom_components/myskoda/__init__.py:167
integration: MySkoda (documentation, issues)
First occurred: 9:26:04 AM (1 occurrences)
Last logged: 9:26:04 AM

Login with myskoda failed:
Traceback (most recent call last):
  File "/config/custom_components/myskoda/__init__.py", line 167, in async_migrate_entry
    await myskoda.connect(entry.data["email"], entry.data["password"])
  File "/usr/local/lib/python3.13/site-packages/myskoda/myskoda.py", line 130, in connect
    await self.authorization.authorize(email, password)
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 77, in authorize
    self.idk_session = await self._get_idk_session()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 216, in _get_idk_session
    login_meta = await self._initial_oidc_authorize(verifier)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 116, in _initial_oidc_authorize
    return self._extract_csrf(await response.text())
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/myskoda/auth/authorization.py", line 68, in _extract_csrf
    raise CSRFError
myskoda.auth.authorization.CSRFError

**Comment by prvakt** [comment]
API was down in the morning. Can you check it now?

**Comment by une18** [comment]
Redownload from HACS fixed it.

**Comment by MilanDasek** [comment]
It is not solved on my side.

I redownloaded via HACKs, restarted 5 time, still the same.
