### ISSUE TITLE
Most sensors missing in 1.21.0 / HA 2025.3

### ISSUE THREAD

**Issue by requiemmg** [skodaconnect/homeassistant-myskoda#651]
Updated to HA 2025.3 and MySkoda 1.21.0 today. Integration fully functional before that.

Skoda Enyaq. Car is online, MySkoda App works, logged in and out.

Now only odometer, next inspection and software version show up, all others are "unknown".

Nothing in Core logs. Screenshot of debug lig attached. Deleting and recreating the car in the integration does not change anything.

![Image](https://github.com/user-attachments/assets/9ec4c852-43f3-492c-ae24-18e8d35c5855)
![Image](https://github.com/user-attachments/assets/5934d567-51da-4505-bf51-82795df6d276)

**Comment by mvzut** [comment]
Same here

**Comment by ProfiTiger** [comment]
also same here

**Comment by shoey79** [comment]
I found this log on my HA:

Logger: homeassistant.util.package
Source: util/package.py:159
First occurred: 10:34:07 (3 occurrences)
Last logged: 10:34:08
Unable to install package myskoda==0.20.0: × No solution found when resolving dependencies: ╰─▶ Because myskoda==0.20.0 depends on paho-mqtt>=1,<2 and paho-mqtt==2.1.0, we can conclude that myskoda==0.20.0 cannot be used. And because you require myskoda==0.20.0, we can conclude that your requirements are unsatisfiable.

**Comment by jeroenribbink** [comment]
> I found this log on my HA:
> 
> Logger: homeassistant.util.package Source: util/package.py:159 First occurred: 10:34:07 (3 occurrences) Last logged: 10:34:08 Unable to install package myskoda==0.20.0: × No solution found when resolving dependencies: ╰─▶ Because myskoda==0.20.0 depends on paho-mqtt>=1,<2 and paho-mqtt==2.1.0, we can conclude that myskoda==0.20.0 cannot be used. And because you require myskoda==0.20.0, we can conclude that your requirements are unsatisfiable.

This is fixed in the update of yesterday. If you do not see the update in HACS. Download the integration again with the button “download again” in the context menu in the upper right corner of the HACS integration information page.

**Comment by requiemmg** [comment]
Please read the bug report, this is NOT due to not havingvthe current update installed.

**Comment by shoey79** [comment]
> > I found this log on my HA:
> > Logger: homeassistant.util.package Source: util/package.py:159 First occurred: 10:34:07 (3 occurrences) Last logged: 10:34:08 Unable to install package myskoda==0.20.0: × No solution found when resolving dependencies: ╰─▶ Because myskoda==0.20.0 depends on paho-mqtt>=1,<2 and paho-mqtt==2.1.0, we can conclude that myskoda==0.20.0 cannot be used. And because you require myskoda==0.20.0, we can conclude that your requirements are unsatisfiable.
> 
> This is fixed in the update of yesterday. If you do not see the update in HACS. Download the integration again with the button “download again” in the context menu in the upper right corner of the HACS integration information page.

I've just deleted my comment, yes, I spotted that it wasn't prompting me to update, so manually updated and rebooted.  However I am also now getting "Unknown" for all sensors, will will scan the logs for clues.

**Comment by WebSpider** [comment]
Anyone encountering this specific problem, please downgrade to 1.21-beta2 and give us details on your install.

**Comment by dvx76** [comment]
@jeroenribbink which HA version?

All, this is widespread, no need for more _me too_ messages. Just add a 👍 to the first message if you want to show you have the same issue. Thanks 😄

**Comment by jeroenribbink** [comment]
> [@jeroenribbink](https://github.com/jeroenribbink) which HA version?
> 
> All, this is widespread, no need for more _me too_ messages. Just add a 👍 to the first message if you want to show you have the same issue. Thanks 😄

I am sorry. Running HA 2025.3.0

**Comment by mvzut** [comment]
Upgrading the MySkoda plugin to 1.21 resolves the error messages, but nevertheless none of my sensors are working (in HA 2025.3.0)

**Comment by jeroenribbink** [comment]
> Upgrading the MySkoda plugin to 1.21 resolves the error messages, but nevertheless none of my sensors are working (in HA 2025.3.0)

Does it works if you revert to beta2. Like me, it is working correctly after reverting. I don't know how this is possible because there are no changes (visible) between these versions.

**Comment by nils512** [comment]
HA 2025.3.0:
v1.21.0-beta1 works
v1.21.0-beta2 does not work
v1.21.0 does not work

**Comment by mvzut** [comment]
Indeed, v1.21.0-beta2 works for me as well. So if you really need this plugin (like me, I am depending on it for automatic low-tariff charging), this is a temporary solution.

**Comment by tisto21** [comment]
> Updated to HA 2025.3 and MySkoda 1.21.0 today. Integration fully functional before that.
> 
> Skoda Enyaq. Car is online, MySkoda App works, logged in and out.
> 
> Now only odometer, next inspection and software version show up, all others are "unknown".
> 
> Nothing in Core logs. Screenshot of debug lig attached. Deleting and recreating the car in the integration does not change anything.
> 
> ![Image](https://github.com/user-attachments/assets/9ec4c852-43f3-492c-ae24-18e8d35c5855) ![Image](https://github.com/user-attachments/assets/5934d567-51da-4505-bf51-82795df6d276)

**Comment by tisto21** [comment]
Same here, updated HA to 2025.3 and myskoda to 1.21.0. Looks same as above for me. In my case my Skoda Enyaq has no connection to the skoda servers since 2 days. So it seems to be a problem of my Enyaq or Skoda (and maybe of HA also).

**Comment by seborix** [comment]
work for me with 1.21 beta 2 but not 1.21

**Comment by FranSooS** [comment]
Skoda Kodiaq. 
Here the problem after updating to 2025.3 that the whole integration does not start.
1.20.0

**Comment by WebSpider** [comment]
> Skoda Kodiaq. 
> Here the problem after updating to 2025.3 that the whole integration does not start.
> 1.20.0
> 
Thats not what this issue is about, please update to 1.21beta2.

**Comment by FranSooS** [comment]
Just had the update 1.21 installed inside and everything is working properly.
Thanks for the help😀

**Comment by pvh0** [comment]
1.21 suddenly started working again two hours again.

**Comment by nils512** [comment]
> Just had the update 1.21 installed inside and everything is working properly. Thanks for the help😀

i tried to update to 1.21 again this morning, but got the same error again.
Downgrade to v1.21.0-beta1 helped that my Enyaq is visible again in Home-Assistant.

**Comment by dvx76** [comment]
Should be fixed in v1.21.1

**Comment by VedMod** [comment]
I have still the problem that a lot of the sensors are unknown, but my car is still on the 3.7 Software, could this a problem?
And also the car is already in Year 3+, so i don't have anymore the paid connect service part. (I have no clue if this makes a different here :D )

Also is there any permission setting in the app  i have to be set to "allow"/"enabled" ?

**Comment by pencoe** [comment]
> I have still the problem that a lot of the sensors are unknown, but my car is still on the 3.7 Software, could this a problem? And also the car is already in Year 3+, so i don't have anymore the paid connect service part. (I have no clue if this makes a different here :D )

My Citigo-e is in Year 5 and working... Don't know, what you are meaning with "is on the 3.7 Software", but i'm pretty sure that the Software Level in my Citigo is old.

> Also is there any permission setting in the app i have to be set to "allow"/"enabled" ?

IMHO No.

I had a few entities where HA said "This entitity is no longer offered by this integration", most of them were fixed by deleting the Car and then add it again..

**Comment by VedMod** [comment]
> My Citigo-e is in Year 5 and working... Don't know, what you are meaning with "is on the 3.7 Software", but i'm pretty sure that the Software Level in my Citigo is old.
> 
Sorry, i was just thinking about my car (Enyaq). The 3.7 Software is "very" old. The current one is 5.2 or higher and had a lot of changes/improvments for the Enyaq. But since Skoda (VW) is still not able to do real Over the air updates, the "Old" Enyaqs (Production Year 2021/22) are not getting the update direct....
