### ISSUE TITLE
Car mileage unknown

### ISSUE THREAD

**Issue by balint-s** [skodaconnect/homeassistant-myskoda#930]
### Please confirm:

- [x] I have searched the existing open and closed issues this problem
- [x] I have updated the integration to the latest available version

### Home Assistant installation and version

2025.10.2

### Car model

Octavia

### Integration version

1.28.8

### Bug Description

Couple of days ago, the mileage entity became unknown. I also noticed that the mileage value is now missing from the official Skoda app as well. Could this be an API breaking change? 

Looking at the diagnostics, the data is available in the health endpoint response. Maintenance endpoint response does not have maintanence_report.

### Debug Logs

```bash
{
              "type": "get",
              "vehicle_id": 0,
              "success": true,
              "endpoint": "health",
              "raw": "{\"capturedAt\": \"2025-10-30T14:37:15Z\", \"mileageInKm\": 195208, \"warningLights\": [{\"category\": \"ASSISTANCE\", \"defects\": []}, {\"category\": \"COMFORT\", \"defects\": []}, {\"category\": \"BRAKE\", \"defects\": []}, {\"category\": \"ENGINE\", \"defects\": []}, {\"category\": \"LIGHTING\", \"defects\": []}, {\"category\": \"TIRE\", \"defects\": []}, {\"category\": \"OTHER\", \"defects\": []}]}",
              "url": "/v1/vehicle-health-report/warning-lights/TMOCKAA0AA000000",
              "result": {
                "timestamp": "2025-10-31T13:11:25.575695+00:00",
                "warning_lights": [
                  {
                    "category": "ASSISTANCE",
                    "defects": []
                  },
                  {
                    "category": "COMFORT",
                    "defects": []
                  },
                  {
                    "category": "BRAKE",
                    "defects": []
                  },
                  {
                    "category": "ENGINE",
                    "defects": []
                  },
                  {
                    "category": "LIGHTING",
                    "defects": []
                  },
                  {
                    "category": "TIRE",
                    "defects": []
                  },
                  {
                    "category": "OTHER",
                    "defects": []
                  }
                ],
                "mileage_in_km": 195208,
                "captured_at": "2025-10-30T14:37:15+00:00"
              },
              "error": null
            },



2025-10-31 14:08:18.150 DEBUG (MainThread) [myskoda.myskoda] IDK Authorization was successful.
2025-10-31 14:08:18.150 DEBUG (MainThread) [myskoda.myskoda] MySkoda ready.
2025-10-31 14:08:18.492 DEBUG (MainThread) [custom_components.myskoda.coordinator] Performing initial data fetch for vin XXX
2025-10-31 14:08:19.139 DEBUG (MainThread) [custom_components.myskoda.coordinator] MySkoda has finished starting up. Scheduling post-start tasks for vin XXX.
2025-10-31 14:08:19.140 DEBUG (MainThread) [custom_components.myskoda.coordinator] Could not connect to MQTT. Waiting for regular poll
2025-10-31 14:08:19.140 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 0.648 seconds (success: True)
2025-10-31 14:08:19.148 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 0.000 seconds (success: True)
2025-10-31 14:08:19.218 DEBUG (MainThread) [custom_components.myskoda.device_tracker] 'unmodified_exterior_front' not found, falling back to 'unmodified_exterior_side'.
2025-10-31 14:08:29.150 DEBUG (MainThread) [custom_components.myskoda.coordinator] Performing scheduled refresh of all data for vin XXX
2025-10-31 14:08:29.823 DEBUG (MainThread) [custom_components.myskoda.coordinator] Finished fetching myskoda data in 0.674 seconds (success: True)
2025-10-31 14:08:29.824 DEBUG (MainThread) [custom_components.myskoda.coordinator] Received update notification for XXX
2025-10-31 14:08:29.838 DEBUG (MainThread) [custom_components.myskoda.coordinator] Manually updated myskoda data
2025-10-31 14:08:29.846 DEBUG (MainThread) [custom_components.myskoda.device_tracker] 'unmodified_exterior_front' not found, falling back to 'unmodified_exterior_side'.
```

**Comment by WebSpider** [comment]
Interesting. Could you see if you can attach the diagnostics?

**Comment by balint-s** [comment]
Absolutely.
[config_entry-myskoda-01K8X5VC08F3F3XMEZHAB4M2GQ.json](https://github.com/user-attachments/files/23267137/config_entry-myskoda-01K8X5VC08F3F3XMEZHAB4M2GQ.json)

**Comment by WebSpider** [comment]
```json
{
                  "id": "VEHICLE_HEALTH_INSPECTION",
                  "statuses": [
                    "LOCATION_DATA_DISABLED",
                    "LICENSE_EXPIRED"
                  ]
                },
```

This is the reason. Thanks for this edge case, we should fix this so that we fall back to available data.

**Comment by balint-s** [comment]
Cool, thank you for taking a look at this!

**Comment by WebSpider** [comment]
PS: It will probably start working again if you renew the subscription 😉

**Comment by balint-s** [comment]
I wasn't aware I had a subscription. The app most certainly did not have any features available. I have been using HA to track the miles which I found very useful.

**Comment by balint-s** [comment]
Unfortunately this does not appear to fix the issue. Did a bit of debugging an it seems as if the health is not available on the `vehicle` object in the coordinator. As a dirty hack, monkey patching the `vehicle.health` with `await self.myskoda.get_health(self.vin)` seems to work. This would likely mean that the issue is with the underlying MySkoda lib?
