### ISSUE TITLE
Button FLASH & HONK_FLASH

### ISSUE THREAD

**Issue by caspariello** [skodaconnect/homeassistant-myskoda#944]
### Please confirm:

- [x] I have searched the existing open and closed issues this problem
- [x] I have updated the integration to the latest available version

### Home Assistant installation and version

2025.11.1

### Car model

SKODA KODIAQ

### Integration version

1.28.9

### Latest working release

1.28.8

### Bug Description

The FLASK and HONK_FLASH buttons are not present. They are present and functional from the app.

### Debug Logs

```bash

```

**Comment by WebSpider** [comment]
Please attach your diagnostics

**Comment by WebSpider** [comment]
Also, I am currently seeing quite some API errors from the MySkoda side. It could be that this is solved by a restart of the integration

**Comment by caspariello** [comment]
Here my diagnotics (I hope :-)). I tried to restart the integration but it's always the same.

[myskoda-01K9PA2TDASX0FGJFN8QZTHBEZ-Škoda Kodiaq-7a5125dfa287667c6495eb1acb508f93.json](https://github.com/user-attachments/files/23456146/myskoda-01K9PA2TDASX0FGJFN8QZTHBEZ-Skoda.Kodiaq-7a5125dfa287667c6495eb1acb508f93.json)

<img width="347" height="268" alt="Image" src="https://github.com/user-attachments/assets/debe1573-f593-42ab-a970-a303aa03cbf6" />


Thank's for your attention

**Comment by WebSpider** [comment]
I am puzzled by this. Your car advertises it supports honk and flash, so we should create the entities. Are you sure they are not hidden / disabled?

**Comment by caspariello** [comment]
> I am puzzled by this. Your car advertises it supports honk and flash, so we should create the entities. Are you sure they are not hidden / disabled?

No, if I had disabled them, I should see something like this:

![Image](https://github.com/user-attachments/assets/cbd4ab44-bb12-455e-a2d7-b95b013d13c7)

But here you can see that nothing is disabled.

![Image](https://github.com/user-attachments/assets/44d10053-7991-410b-8521-bc6a54992c60)

The total detected entities are 35, and if I remember correctly, before the fix, there were 37.

![Image](https://github.com/user-attachments/assets/bac5c0c1-bcd9-4e52-adfc-64cf38558460)

The machine actually has the functions.

![Image](https://github.com/user-attachments/assets/0646dbb7-84f5-4cc2-ac40-b62f13a97244)

For the record, I had previously used them with the integration. I'll try this evening, and even though they're available, maybe they don't work anymore, even via the app.

**Comment by caspariello** [comment]
I can confirm that both work using the app. Just to be sure, I reloaded the integration, but they're still missing. Otherwise, everything works fine. 🙂

**Comment by WebSpider** [comment]
Thanks, we'll need to dig into what changed related to the buttons in our latest update, this was unintended.

**Comment by racoon2code** [comment]
@caspariello Just a quick idea that might help narrow this down:

Could you check whether the MySkoda integration is currently running in read-only mode?
If this option is enabled, the Honk and Flash buttons will not be created, even if the vehicle reports the correct capability.

You can verify this here:

Settings → Devices & Services → MySkoda → Configure

There should be an option like “Read-only.”
If it’s enabled, try turning it off and then reload the integration.
In my tests:

Read-only ON → buttons disappear

Read-only OFF → buttons appear again and work correctly

Maybe this helps to pinpoint the issue 🙂

**Comment by caspariello** [comment]
> [@caspariello](https://github.com/caspariello)Ecco un'idea veloce che potrebbe aiutare a restringere il campo:
> 
> Potresti verificare se l'integrazione MySkoda è attualmente in esecuzione in modalità di sola lettura? Se questa opzione è abilitata, i pulsanti Clacson e Lampeggiante non verranno creati, anche se il veicolo segnala la funzionalità corretta.
> 
> Puoi verificarlo qui:
> 
> Impostazioni → Dispositivi e servizi → MySkoda → Configura
> 
> Dovrebbe esserci un'opzione come "Sola lettura". Se è abilitata, prova a disattivarla e poi ricarica l'integrazione. Nei miei test:
> 
> Sola lettura ON → i pulsanti scompaiono
> 
> Sola lettura OFF → i pulsanti vengono visualizzati di nuovo e funzionano correttamente
> 
> Forse questo aiuta a individuare il problema 🙂

Hi, I actually found the read-only option set to true. When I unchecked the entities, they reappeared.

I honestly don't remember if it was true. Since I entered the PIN and had the door lock/unlock entity, I probably didn't notice it.

Thanks a lot :-)
